"""Constants for the Relative Light Group integration."""

from __future__ import annotations

DOMAIN = "relative_light_group"

CONF_HIDE_MEMBERS = "hide_members"
CONF_ALL = "all"
CONF_REMEMBER_ON_STATE = "remember_on_state"
CONF_RESTORE_INDIVIDUAL_BRIGHTNESS = "restore_individual_brightness"
CONF_REMEMBER_BRIGHTNESS = "remember_brightness"
CONF_DEBOUNCE_ENABLED = "debounce_enabled"
CONF_DEBOUNCE_TIME = "debounce_time"
CONF_BRIGHTNESS_STRATEGY = "brightness_strategy"
CONF_MEMBER_DIAGNOSTICS = "member_diagnostics"

BRIGHTNESS_STRATEGY_AVERAGE = "average"
BRIGHTNESS_STRATEGY_MEDIAN = "median"
BRIGHTNESS_STRATEGY_MAX = "max"
BRIGHTNESS_STRATEGY_MIN = "min"

BRIGHTNESS_STRATEGIES = (
    BRIGHTNESS_STRATEGY_AVERAGE,
    BRIGHTNESS_STRATEGY_MEDIAN,
    BRIGHTNESS_STRATEGY_MAX,
    BRIGHTNESS_STRATEGY_MIN,
)

DEFAULT_DEBOUNCE_ENABLED = True
DEFAULT_DEBOUNCE_TIME = 2000
DEFAULT_BRIGHTNESS_STRATEGY = BRIGHTNESS_STRATEGY_AVERAGE
DEFAULT_MEMBER_DIAGNOSTICS = False
